InfoEarthFrame.Web.Next/Controllers/BaseController.cs
using InfoEarthFrame.Common;
using InfoEarthFrame.Web.Next.Filters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InfoEarthFrame.Web.Next.Controllers
{
    [CustomAuthFilterAttribute]
    public class BaseController : System.Web.Mvc.Controller
    {
        public JsonResult2 Json2(object data, JsonRequestBehavior jsonRequestBehavior = JsonRequestBehavior.AllowGet)
        {
            var result = new JsonResult2();
            result.Data = data;
            result.JsonRequestBehavior = jsonRequestBehavior;
            return result;
        }

        [HttpPost]
        public JsonResult ChangeLang()
        {
            var currentLang = UserConfigContext.CurrentLang;
            if (currentLang == "zh-cn")
            {
                UserConfigContext.CurrentLang = "en";
            }
            else
            {
                UserConfigContext.CurrentLang = "zh-cn";
            }
            return Json2(new HttpResponseResult
            {
                Code = 0
            });
        }
     
        public ActionResult SelectTree(string apiPath)
        {
            ViewBag.ApiPath = apiPath;
            return View("~/Views/Shared/_SelectTreeLayout.cshtml");
        }

        public ActionResult UploadFile(string mainId, string folderName, string uploadUrl, string ext, string okCallback, string uploadFailureCallback="")
        {
            ViewBag.Url = GetApiUrl(uploadUrl) + "?mainId=" + mainId + "&folderName=" + HttpUtility.UrlEncode(folderName) + "&okCallback=" + okCallback + "&failureCallback=" + uploadFailureCallback;
            ViewBag.Ext = ext;
            return View("~/Views/Shared/_UploadLayout.cshtml");
        }


        public ActionResult _UserList()
        {
            return View("~/Views/Shared/_UserList.cshtml");
        }

        public JsonResult ChangeLang(string lang)
        {
            UserConfigContext.CurrentLang = lang;
            return Json2(new HttpResponseResult
            {
                Code = 0
            });
        }

        public static string GetApiUrl(string rawUrl)
        {
            return ConfigContext.Current.ApiConfig.BaseUrl+"/api" + rawUrl;
        }

        public JsonResult GetPDFFile(string filePath)
        {
            var ext = Path.GetExtension(filePath);
            var ftp=ConfigContext.Current.FtpConfig["package"];
            var ftpPath=filePath.Replace(ftp.Site, "");
            var pdfPath=ftpPath.Replace(ext, ".pdf");
            pdfPath = TempDirectory + "\\" + pdfPath.Replace("/", "\\");
            pdfPath = pdfPath.Replace("\\\\", "\\");

            //判断PDF文件是否存在
            var file = new FileInfo(pdfPath);
            if (!file.Exists)
            {
                //去FTP下载
                using (var client = new FtpHelper(ftp))
                {
                    var srcPath=pdfPath.Replace(".pdf", ext);
                    client.Get(srcPath, ftpPath);

                    //TODO:注释了
                  PDFConverter.Convert(srcPath, pdfPath);

                }
            }


            return Json2(new HttpResponseResult
            {
                Code = 0,
                Data ="/"+pdfPath.Replace(Server.MapPath("~"), "").Replace("\\","/")
            });
        }



        protected string TempDirectory
        {
            get
            {
                var dir = Path.Combine(Server.MapPath("~"), "TempFile");
                if (!Directory.Exists(dir))
                {
                    Directory.CreateDirectory(dir);
                }

                return dir;
            }
        }
    }

    public class JsonResult2 : JsonResult
    {
        public override void ExecuteResult(ControllerContext context)
        {
            context.HttpContext.Response.ContentType = "application/json";
            context.HttpContext.Response.Write(JsonConvert.SerializeObject(this.Data));
        }
    }
}

InfoEarthFrame.Web.Next/Controllers/DataEditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InfoEarthFrame.Web.Next.Controllers
{
    public class DataEditorController : BaseController
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowMap(string mainId="",string layerNames="")
        {
            ViewBag.MainId = mainId;
            ViewBag.LayerNames = HttpUtility.UrlDecode(layerNames);
            return View();
        }

 

        public ActionResult StyleList()
        {
            return View();
        }

        public ActionResult EditAttribute()
        {
            return View();
        }


        public ActionResult AddAttribute()
        {
            return View();
        }

    }
}

InfoEarthFrame.Web.Next/Controllers/dataManagerController.cs
using InfoEarthFrame.Application;
using InfoEarthFrame.Application.SystemUserApp;
using InfoEarthFrame.Application.SystemUserApp.Dtos;
using InfoEarthFrame.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace InfoEarthFrame.Web.Next.Controllers
{
    public class DataManagerController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddOrEditType()
        {
            return View();
        }

        public ActionResult SelectPackageSource()
        {
            return View();
        }

        public ActionResult AddOrEditPackage()
        {
            return View();
        }

        public ActionResult AddOrEditRarPackage()
        {
            return View();
        }


        public new ActionResult File(string mainId, string folderName)
        {
            if (folderName.EndsWith("图层"))
            {
                ViewBag.Header = "支持MapGIS或ArcGIS数据格式的文件包上传(*.zip|*.rar)";
                ViewBag.UploadUrl = "/DataManager/UploadLayerFile";
                ViewBag.Ext = "zip|rar";
                ViewBag.UploadFailureCallback = "uploadLayerFailureCallback";
            }
            else if (folderName.EndsWith("制图文件") || folderName.EndsWith("系统库"))
            {
                ViewBag.Header = "支持任意文件上传";
                ViewBag.UploadUrl = "/DataManager/UploadFile";
                ViewBag.Ext = "";
            }
            else if (folderName.EndsWith("文档"))
            {
                ViewBag.Header = "支持Word或Excel文件格式上传(*.doc|*.docx|*.xls|*.xlsx)";
                ViewBag.UploadUrl = "/DataManager/UploadFile";
                ViewBag.Ext = "doc|docx|xls|xlsx";

                return View("~/Views/DataManager/Document.cshtml");
            }
            else if (folderName.EndsWith("说明书"))
            {
                ViewBag.Header = "支持Word文件格式上传(*.doc|*.docx)";
                ViewBag.UploadUrl = "/DataManager/UploadFile";
                ViewBag.Ext = "doc|docx";

                return View("~/Views/DataManager/Document.cshtml");
            }
            else if (folderName.EndsWith("栅格图"))
            {
                ViewBag.Header = "支持图片文件格式上传(*.jpg|*.gif|*.png|*.jpeg|*.bmp)";
                ViewBag.UploadUrl = "/DataManager/UploadFile";
                ViewBag.Ext = "jpg|gif|png|jpeg|bmp";

                ViewBag.Url = GetApiUrl("/DataManager/UploadFile") + "?ftpName=layer&mainId=" + mainId + "&folderName=" + HttpUtility.UrlEncode(folderName);

                return View("~/Views/DataManager/Image.cshtml");
            }
            return View();
        }

        public ActionResult MetaData(string mainId, string folderName)
        {
            return View();
        }

        public ActionResult ErrorDetail(string mainId)
        {
            return View();
        }

        public ActionResult UploadMetaDataFile()
        {
            return View();
        }
    }
}

InfoEarthFrame.Web.Next/Views/DataManager/AddOrEditType.cshtml
@{
    Layout = "~/Views/Shared/_MainContentLayout.cshtml";
    ViewBag.Title = "增加或编辑类型";
}

<div class="layui-fluid" style="padding:0px">
    <div class="layui-card">
        <div class="layui-card-body" id="app">
            <form class="layui-form" action="" lay-filter="component-form-group">
                <div class="layui-form-item">

                    <label class="layui-form-label">上级分类</label>
                    <div class="layui-input-block">
                        <input type="text" name="ParentName" id="txtParentName" v-model="model.ParentName" onclick="showSelectTreeDlg()" class="layui-input" readonly>
                    </div>

                </div>

                <div class="layui-form-item">

                    <label class="layui-form-label">分类名称</label>
                    <div class="layui-input-block">
                        <input type="text" name="ClassName" id="txtClassName" lay-verify="required" v-model="model.ClassName" autocomplete=" off" class="layui-input">
                    </div>

                </div>
                <button class="layui-btn" lay-submit="" lay-filter="component-form" id="btnSubmit" style="display:none">立即提交</button>
                <input type="hidden" name="ParentID" id="hidParentID" v-model="model.ParentID" />
                <input type="hidden" name="Id" v-model="model.Id" />
            </form>
        </div>
    </div>
</div>

@section script
{
    <script>
        var submitCallback;
        var oldClassName = ''
        var model = {
            ParentName: decodeURIComponent('@Request.QueryString["parentName"]'),
            ParentID: '@Request.QueryString["ParentID"]',
            Id: '@Request.QueryString["id"]'
        };
        layui.initModule(['form'], function () {
            var $ = layui.$, form = layui.form;

            initModel();

            form.render(null, 'component-form-group');

            /* 监听提交 */
            form.on('submit(component-form)', function (data) {
                var isValid = false;

                $.get({
                    async: false,
                    url: Base.getApiUrl("/DataManager/GetClassNameStatus"),
                    data: {
                        rdm: Math.random(),
                        parentId: $("#hidParentID").val(),
                        className: $.trim($("#txtClassName").val()),
                        oldClassName: oldClassName
                    },
                    success: function (resp) {
                        if (resp.code != 0) {
                            alert(resp.message);
                        }
                        else {
                            isValid = true;
                        }
                    }
                });

                if (model.Id && $("#hidParentID").val() == model.Id) {
                    alert('上级分类不能与本类相同');
                    isValid = false;
                }

                if (isValid) {
                    $.post({
                        url: Base.getApiUrl("/DataManager/AddOrEditType"),
                        data: data.field,
                        success: function (resp) {
                            if (resp.code == 0) {
                                parent.layer.closeAll();
                                submitCallback(model.ParentID, {
                                    id: resp.data.Id,
                                    label: resp.data.ClassName
                                });
                            }
                        }
                    })
                }
                return false;
            });

            layui.autoHeight();
        });


        function initModel() {
            if (model.Id) {
                $.get({
                    url: Base.getApiUrl("/DataManager/GetType"),
                    async: false,
                    data: {
                        id: model.Id
                    },
                    success: function (resp) {
                        oldClassName = resp.data.ClassName;
                        initVue(resp.data)
                    }
                });
            }
            else {
                initVue(model);
            }
        };


        function initVue(data) {
            new Vue({
                el: '#app',
                data: {
                    LangConfig: LangConfig,
                    model: data
                }
            });
        }

        function doSubmit(callback) {
            submitCallback = callback;
            $("#btnSubmit").click();
        }


        function showSelectTreeDlg() {
            parent.layui.showDlg({
                title: '选择分类',
                content: '@Url.Action("SelectTree","Base")?apiPath=/DataManager/GetMappingTree',
                area: ['13%'],
                closeBtn: false,
                yes: function (index, layero) {
                    var iframeWin = parent.window[layero.find('iframe')[0]['name']]; //得到iframe页的窗口对象，执行iframe页的方法
                    if (iframeWin.isValid()) {
                        $("#hidParentID").val(iframeWin.currentCode);
                        $("#txtParentName").val(iframeWin.currentName);
                        parent.layer.close(index);
                    }
                }
            });
        }
    </script>
}

InfoEarthFrame.Web.Next/Views/DataManager/Document.cshtml
@{
    Layout = "~/Views/Shared/_MainContentLayout.cshtml";
}

@section css
{
  <link href="@Url.Content("~/Content/layuiadmin/style/template.css")" rel="stylesheet" />
    <style>
        .cmdlist-container {
         margin-top:10px
        }
        .layui-form-checkbox {
         position:absolute !important;
         right:60px;
         top:-25px
        }
        .layui-input-block {
            position: relative !important;
        }
    </style>
}
<div class="layui-fluid" style="padding:0px">
    <div class="layui-card layui-form">
        <div class="layui-card-header">
            @ViewBag.Header 
        </div>
        <div class="layui-card-body" style="padding:0px">
            <div class="layui-fluid layadmin-cmdlist-fluid" style="padding:0px 0px 0px 15px">
                <div class="layui-btn-group">
                    <button class="layui-btn layui-btn-primary layui-btn-sm" onclick="uploadFile()" data-permession-button="编辑"><i class="layui-icon" onclick="uploadFile()">&#xe681;</i>上传</button>
                    <button class="layui-btn layui-btn-primary layui-btn-sm" onclick="removeFile()" data-permession-button="删除"><i class="layui-icon" onclick="removeFile()"></i>删除</button>
                </div>
                <button class="layui-btn layui-btn-primary layui-btn-sm" onclick="initGrid()"><i class="layui-icon">&#xe9aa;</i>刷新</button>
                <div class="layui-row layui-col-space30" id="content">
                </div>
            </div>

        </div>
    </div>
    @section script
{
        <script>

            var ids = [];

            layui.initModule(['laypage','form'], function () {


                initGrid();
            });


            function initGrid()
            {
                $.get({
                    url: Base.getApiUrl("/DataManager/GetUploadFiles"),
                    data: {
                        mainId: '@Request.QueryString["mainId"]',
                        folderName: decodeURIComponent('@Request.QueryString["folderName"]')
                    },
                    success: function (resp)
                    {
                        $("#content").html('');
                        $.each(resp.data, function (idx, ele) {
                            var image = 'file-128.png';
                            if (ele.Ext.indexOf(".doc") >= 0)
                            {
                                image = 'word-128.png';
                            }
                            else if (ele.Ext.indexOf(".xls") >= 0)
                            {
                                image = 'excel-128.png';
                            }
                            image = '@Url.Content("~/Content/images/")' + image;
                           var  sb = '      <div class="layui-col-md2 layui-col-sm4"><div class="cmdlist-container">';
                            sb += "                            <a href=\"javascript:viewFile('"+ele.FilePath+"','"+ele.name+"')\">";
                            sb += "                                <img src=" + image + " title='" + ele.name + "'>";
                            sb += '                            </a>';
                            sb += '                            <a href="javascript:;" title="' + ele.name + '">';
                            sb += '                                <div class="cmdlist-text">';
                            sb += "                                    <p class=\"info\">" + ele.name + "</p>";
                            sb += '                                </div>';
                            sb += '                                <div class="layui-form-item">';
                            sb += '                                    <label class="layui-form-label"> </label>';
                            sb += '                                    <div class="layui-input-block">';
                            sb += "                                        <input type=\"checkbox\" title=\"\" value=" + ele.id + " lay-skin=\"primary\" lay-filter='file'>";
                            sb += '                                    </div>';
                            sb += '                                </div>';
                            sb += '                            </a>';
                            sb += '                        </div>';
                            sb += '   </div>';

                            $("#content").append(sb);
                        });
                        Base.initPermession(window.parent.parent.location.href);
                        layui.form.render();
                        layui.form.on('checkbox(file)', function (data) {
                            if (data.elem.checked) {
                                ids.push(data.elem.value);
                            }
                            else {
                                ids.remove(data.elem.value);
                            }
                        });

                        $(".cmdlist-container").hover(function () {
                            $(this).css("border", "none");
                        })
                    }
                })
            }


            function uploadFile() {
                parent.layui.showDlg({
                    title: '上传文件',
                    content: '@Url.Action("UploadFile")?mainId=@Request.QueryString["mainId"]&folderName=@Request.QueryString["folderName"]' + "&uploadUrl=" + '@ViewBag.UploadUrl' + "&ext=@ViewBag.Ext",
                    area: ['80%', '80%'],
                    yes: function (index, layero) {
                    },
                    cancel: function (index, layero) {
                        initGrid();
                        parent.layer.close(index);
                    },
                    btn: []
                });
            }

            function removeFile() {
                if (ids.length == 0) {
                    alert('请选择文件');
                    return;
                }

                confirm('是否删除', function () {
                    $.post({
                        url: Base.getApiUrl("/DataManager/RemoveFile"),
                        data: { "": ids.join(",") },
                        success: function (resp) {
                            if (resp.code == 0) {
                                initGrid();
                                layer.closeAll();
                            }
                        }
                    })
                });
            }


            function viewFile(filePath,fileName)
            {
                debugger
                Base.viewFile({
                    getPDFFileUrl: "@Url.Action("GetPDFFile","Base")",
                    filePath: filePath,
                    fileName: fileName
                });
            }
        </script>
    }

InfoEarthFrame.Web.Next/Views/DataManager/ErrorDetail.cshtml
@{
    Layout = "~/Views/Shared/_MainContentLayout.cshtml";
}
@section css
{
<style>
    .layui-elem-field legend {
        font-weight: normal !important;
        font-size: 14px !important;
    }  
    </style>  
}
<div style="padding:0px" id="msg-container">
    @*<div class="layui-card">
        <div class="layui-card-header">
            <blockquote class="layui-elem-quote" style="margin-bottom:5px" id="subtitle">地理图层</blockquote>
        </div>
        <div class="layui-card-body" style="padding:0px">

        </div>
    </div>*@
</div>

@section script
{
    <script>
        layui.initModule([], function () {

            initErrorMsg();
        });

        function initErrorMsg() {
            $.get({
                url: Base.getApiUrl("/DataManager/GetErrorMsg"),
                data: {
                    mainId: '@Request.QueryString["mainId"]'
                },
                success: function (resp) {
                    $("#msg-container").html('');
                    if (resp.data.length > 0) {
                        $.each(resp.data, function (index, ele) {


                            var errs = ele.ErrorInfo;
                            var innerHtml = '';
                            $.each(errs, function (index2, ele2) {
                                innerHtml += '<fieldset class="layui-elem-field">';
                                innerHtml += "  <legend>第" + (index2 + 1) + "处</legend>";
                                innerHtml += "    <div class=\"layui-field-box\">";
                                innerHtml += ele2;
                                innerHtml += "       </div>";
                                innerHtml += "       </fieldset>";
                                //  innerHtml += '<hr class="layui-bg-red">';
                            });

                            $("#msg-container").append(["<div class=\"layui-card\">",
        "        <div class=\"layui-card-header\">",
        "            <blockquote class=\"layui-elem-quote\" style=\"margin-bottom:5px\" id=\"subtitle\">" + ele.Category + "</blockquote>",
        "        </div>",
        "        <div class=\"layui-card-body\" style=\"padding:20px\">",
       innerHtml,
        "        </div>",
        "    </div>"].join(""));
                        });
                    }
                    else {

                        $("#msg-container").append(["<div class=\"layui-card\">",
    "        <div class=\"layui-card-header\">",
    "            <blockquote class=\"layui-elem-quote\" style=\"margin-bottom:5px\" id=\"subtitle\">无问题</blockquote>",
    "        </div>",
    "        <div class=\"layui-card-body\" style=\"padding:20px\">",
   "",
    "        </div>",
    "    </div>"].join(""));
                    }
                    //var index = parent.layer.getFrameIndex(window.name);
                    //parent.layer.iframeAuto(index);
                }
            })
        }
    </script>
}

InfoEarthFrame.Web.Next/Views/DataManager/File.cshtml
@{
    Layout = "~/Views/Shared/_MainContentLayout.cshtml";
}

@section css
{
    <link href="@Url.Content("~/Content/layuiadmin/uploader_ext/uploader/webuploader.css")" rel="stylesheet" />
}
<div class="layui-fluid" style="padding:0px">
    <div class="layui-card">
        <div class="layui-card-header">
            @ViewBag.Header
        </div>
        <div class="layui-card-body" style="padding:0px">
            <table id="file-table" lay-filter="file-table"></table>
            <script type="text/html" id="file-table-toolbar">
                <div class="layui-btn-group">
                    <button class="layui-btn layui-btn-primary layui-btn-sm" onclick="uploadFile()" data-permession-button="编辑"><i class="layui-icon">&#xe681;</i>上传</button>
                    <button class="layui-btn layui-btn-primary layui-btn-sm" onclick="removeFile()" data-permession-button="删除"><i class="layui-icon"></i>删除</button>
                </div>
                <button class="layui-btn layui-btn-primary layui-btn-sm" onclick="initGrid()"><i class="layui-icon">&#xe9aa;</i>刷新</button>
            </script>
        </div>
    </div>
    @section script
{
        <script>



    layui.initModule(['jquery', 'treeGrid', 'layer'], function () {
        initGrid();
        Base.initPermession(window.parent.parent.location.href);
    });


    function initGrid() {
        layui.initTreeGird({
            id: 'file-table'
            , elem: '#file-table'
            , url: Base.getApiUrl("/DataManager/GetUploadFiles")
            , where: {
                mainId: '@Request.QueryString["mainId"]',
                folderName: decodeURIComponent('@Request.QueryString["folderName"]')
            }
            , cols: [[
                //{ type: 'numbers' }
                { type: 'checkbox', sort: true }
                , { field: 'name', width: 300, title: '文件名称', sort: true }
        , { field: 'FileLength', title: '文件长度', align: 'right' }
        , {
            field: 'StorageTime', title: '上传时间', align: 'center', templet: function (d) {
                return Base.Converter.dateTime(d.StorageTime);
            }
        },
        {
            field: 'IsInGeoServer', title: '是否入库', align: 'center', event: 'setSign', templet: function (d) {
                if (d.IsInGeoServer) {
                        return "<button class=\"layui-btn layui-btn-xs\">已入库</button>"
                }
                return "";
            }
        },
             {
                 field: '', title: '', width: 100, align: 'center', event: 'setSign', templet: function (d) {
                     if (d.IsInGeoServer) {
                         return "<button class=\"layui-btn layui-btn-normal layui-btn-xs\" onclick=\"viewFile('" + d.FilePath + "','" + d.name + "','"+d.id+"')\">查看</button>"
                     }
                     return "<button class=\"layui-btn layui-btn-disabled layui-btn-xs\" onclick=\"viewFile('" + d.FilePath + "','" + d.name + "','"+d.id+"')\">查看</button>"
                 }
             }
            ]],
            toolbar: "#file-table-toolbar"
        });

    }


            function viewFile(filePath, fileName, id) {
                if (fileName.toLowerCase().indexOf(".doc") != -1 || fileName.toLowerCase().indexOf(".xls") != -1 || fileName.toLowerCase().indexOf(".pdf")!=-1) {
                    Base.viewFile({
                        getPDFFileUrl: "@Url.Action("GetPDFFile","Base")",
                        filePath: filePath,
                        fileName: fileName
                    });
                }
                else {
                    if (fileName.toLowerCase().indexOf(".shp") != -1) {
                        $.get({
                            url: Base.getApiUrl("/DataEditor/GetDetailById"),
                            data: {
                                layerId: id
                            },
                            // async: false,
                            success: function (resp) {
                                if (resp.code == 0) {
                                    model = resp.data;

                                   top.layui.showDlg({
                                        title: fileName,
                                        content: "@Url.Action("ShowMap", "DataEditor")",
                                        area: ['100%', '100%'],
                                        btn: [],
                                        success: function (layero, index) {
                                            var iframeWin = top.window[layero.find('iframe')[0]['name']]; //得到iframe页的窗口对象，执行iframe页的方法
                                            iframeWin.addLayer(model.LayerAttrTable);
                                        }
                                    });

                                }
                            }
                        })
                    }
                }
            }


    function getCheckData(tableId) {
        return layui.TreeGird.getCheckedIds(tableId);
    }
    function uploadFile() {

        parent.layui.showDlg({
            title: '上传文件',
            content: '@Url.Action("UploadFile")?mainId=@Request.QueryString["mainId"]&folderName=@Request.QueryString["folderName"]' + "&uploadUrl=" + '@ViewBag.UploadUrl' + "&ext=@ViewBag.Ext" + "&UploadFailureCallback=@ViewBag.UploadFailureCallback",
            area: ['80%', '80%'],
            yes: function (index, layero) {
            },
            cancel: function (index, layero) {
                initGrid();
                parent.layer.close(index);
            },
            btn: []
        });
    }

    function removeFile() {
        var ids = getCheckData('file-table')
        if (ids.length == 0) {
            alert('请选择文件');
            return;
        }

        confirm('是否删除', function () {
            $.post({
                url: Base.getApiUrl("/DataManager/RemoveFile"),
                data: { "": ids.join(",") },
                success: function (resp) {
                    if (resp.code == 0) {
                        initGrid();
                        layer.closeAll();
                    }
                }
            })
        });
    }


        </script>
    }

InfoEarthFrame.Web.Next/Views/DataManager/SelectPackageSource.cshtml
@{
    ViewBag.Title = "_SelectAreaLayout";
    Layout = "~/Views/Shared/_MainContentLayout.cshtml";
}

@section css
{

}
<div class="layui-fluid" style="padding:0px">
    <div class="layui-card">
        <div class="layui-card-body" id="app">
            <form class="layui-form" action="" lay-filter="component-form-group">
                <div class="layui-form-item">
                    <label class="layui-form-label">数据来源</label>
                    <div class="layui-input-block">
                        <input type="radio" name="Source" value="1" title="压缩文件">
                        <input type="radio" name="Source" value="2" title="自定义" checked>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section script
{
<script>
    layui.initModule(['form'], function () {
        var form = layui.form;
        form.render(null, 'component-form-group');

        layui.autoHeight();
    });

    function getValue()
    {
        return $("input[name='Source']:checked").val();
    }
    </script>    
}